// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function useState(initial) {
  return React.useReducer((function (param, action) {
                return action;
              }), initial);
}

function useLoading(getter) {
  var match = React.useReducer((function (param, action) {
          return action;
        }), undefined);
  var setData = match[1];
  var data = match[0];
  React.useEffect((function () {
          if (data !== undefined) {
            Curry._1(setData, undefined);
          }
          Curry._1(getter, /* () */0).then((function (result) {
                  Curry._1(setData, Caml_option.some(result));
                  return Promise.resolve(/* () */0);
                }));
          return undefined;
        }), /* array */[getter]);
  return data;
}

exports.useState = useState;
exports.useLoading = useLoading;
/* react Not a pure module */
