// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var blankUi = {
  show_lasers: false,
  selection: null,
  mouse_over: false,
  show_hist: false,
  hovered: null,
  last_mouse_pos: /* tuple */[
    0.0,
    0.0
  ]
};

var wasm = (import('../pkg/zenphoton'));

function withModule(fn) {
  wasm.then((function (wasm) {
          Curry._1(fn, wasm);
          return Promise.resolve(/* () */0);
        }));
  return /* () */0;
}

exports.blankUi = blankUi;
exports.wasm = wasm;
exports.withModule = withModule;
/* wasm Not a pure module */
