// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var wasm = (import('../pkg/zenphoton'));

function withModule(fn) {
  wasm.then((function (wasm) {
          Curry._1(fn, wasm);
          return Promise.resolve(/* () */0);
        }));
  return /* () */0;
}

exports.wasm = wasm;
exports.withModule = withModule;
/* wasm Not a pure module */
