// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Belt_SetString = require("bs-platform/lib/js/belt_SetString.js");

var emptyScene_005 = /* children : array */[];

var emptyScene = /* record */[
  /* id */"",
  /* modified */0,
  /* created */0,
  /* title */undefined,
  /* tags */Belt_SetString.empty,
  emptyScene_005,
  /* parent */undefined
];

exports.emptyScene = emptyScene;
/* No side effect */
