// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_SetString = require("bs-platform/lib/js/belt_SetString.js");

function deserialize_Belt_SetString____t(json) {
  var match = Js_json.classify(json);
  if (typeof match === "number" || match.tag !== 3) {
    return /* Error */Block.__(1, [/* :: */[
                "Expected an array",
                /* [] */0
              ]]);
  } else {
    return Belt_Array.reduce(match[0], /* Ok */Block.__(0, [Belt_SetString.empty]), (function (set, item) {
                  var match = Js_json.classify(item);
                  if (set.tag) {
                    return /* Error */Block.__(1, [set[0]]);
                  } else if (typeof match === "number" || match.tag) {
                    return /* Error */Block.__(1, [/* :: */[
                                "Expected a string in the set array",
                                /* [] */0
                              ]]);
                  } else {
                    return /* Ok */Block.__(0, [Belt_SetString.add(set[0], match[0])]);
                  }
                }));
  }
}

var serialize_Belt_SetString____t = Belt_SetString.toArray;

exports.deserialize_Belt_SetString____t = deserialize_Belt_SetString____t;
exports.serialize_Belt_SetString____t = serialize_Belt_SetString____t;
/* No side effect */
