// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Belt_SetString = require("bs-platform/lib/js/belt_SetString.js");

function genId(param) {
  return Math.random().toString(36).slice(2);
}

function genId$1(param) {
  return genId(/* () */0) + genId(/* () */0);
}

var emptyScene_005 = /* children : array */[];

var emptyScene = /* record */[
  /* id */"",
  /* modified */0,
  /* created */0,
  /* title */undefined,
  /* tags */Belt_SetString.empty,
  emptyScene_005,
  /* parent */undefined,
  /* starred */false
];

exports.genId = genId$1;
exports.emptyScene = emptyScene;
/* No side effect */
